import logging
import json
from typing import Dict, Any, List

from bio_ml_agent.core.agent_base import BaseSubAgent, AgentResult, Confidence, Evidence
from bio_ml_agent.llm_backend import auto_create_backend

log = logging.getLogger("structural.multimer")

class MultimerReasoningAgent(BaseSubAgent):
    """
    A5: Multimer / Complex Reasoning Agent
    Evaluates protein-protein complexes generated by AlphaFold-Multimer.
    Focuses on interface extraction, chain interactions, and complex reliability.
    """

    def __init__(self, model_name: str = "gemini-2.5-pro"):
        super().__init__("MultimerReasoningAgent", model_name)
        self.llm = auto_create_backend(model_name)
        self.complex_context: Dict[str, Any] = {}
        self.interface_report: Dict[str, Any] = {}

    def perceive(self, context: Dict[str, Any]) -> None:
        """Receives multi-chain coordinate distances and ipTM/pTM scores."""
        self.complex_context = context.get("multimer_metrics", {})
        if not self.complex_context:
            log.warning("No complex interaction metrics provided.")
        else:
            log.info("🔗 MultimerReasoningAgent received multichain metrics.")

    def plan(self, goal: str) -> List[str]:
        return [
            "Evaluate global complex confidence (ipTM / pTM scores).",
            "Extract interface candidate residues (inter-chain contacts).",
            "Assess clashes and unphysical interactions.",
            "Generate warnings for low-confidence oligomerizations."
        ]

    def act(self, step: str) -> Any:
        prompt = f"""
        You are an expert in Protein-Protein Interactions (PPI).
        Analyze the following multimeric structure metrics (including inter-chain contacts and interface PAE):
        {json.dumps(self.complex_context, indent=2)}

        Tasks:
        1. Evaluate complex assembly likelihood using AlphaFold confidence criteria (ipTM / interface PAE).
        2. Extract explicit chain-to-chain contact regions (interface candidates).
        3. Issue severe warnings if the complex seems artifactual or driven by disordered tails.

        Respond STRICTLY with a JSON dictionary matching:
        {{
            "complex_likelihood": "High/Medium/Low with justification",
            "interface_candidates": [
                {{"chain_a_residues": [], "chain_b_residues": [], "interface_trust": "High"}}
            ],
            "clash_or_artifact_warnings": ["Warning 1", "Warning 2"]
        }}
        """
        try:
            response = self.llm.chat([{"role": "user", "content": prompt}])
            clean_text = response.replace("```json", "").replace("```", "").strip()
            self.interface_report = json.loads(clean_text)
            log.info("Multimer analysis successfully finalized.")
        except Exception as e:
            log.error(f"Multimer parsing failed: {e}")
            self.interface_report["raw_error_text"] = response

        return "Multimer analysis generated."

    def verify(self, action_result: Any) -> bool:
        return "interface_candidates" in self.interface_report

    def summarize(self) -> AgentResult:
        is_valid = self.verify("")
        conf = Confidence.HIGH if is_valid else Confidence.LOW
        return AgentResult(
            success=is_valid,
            data={"multimer_complex_analysis": self.interface_report},
            confidence=conf,
            evidence=[Evidence("MultimerReasoning", "Inter-chain contact metrics isolated")],
            message="Protein-protein complex evaluation completed."
        )
